bf16: true
cutoff_len: 2048
dataset: kto_dataset_train
dataset_dir: data
ddp_timeout: 180000000
do_train: true
enable_thinking: false
eval_steps: 100
eval_strategy: steps
finetuning_type: lora
flash_attn: auto
gradient_accumulation_steps: 8
include_num_input_tokens_seen: true
learning_rate: 5.0e-07
logging_steps: 5
lora_alpha: 16
lora_dropout: 0.05
lora_rank: 8
lora_target: all
lr_scheduler_type: cosine
max_grad_norm: 1.0
max_samples: 8000
model_name_or_path: /root/autodl-tmp/Qwen3-8B-AWQ
num_train_epochs: 1.0
optim: adamw_torch
output_dir: saves/Qwen3-8B-Thinking-AWQ/lora/train_2025-10-28-10-08-54
packing: false
per_device_eval_batch_size: 4
per_device_train_batch_size: 4
plot_loss: true
pref_beta: 0.5
pref_ftx: 0
pref_loss: sigmoid
preprocessing_num_workers: 16
report_to: tensorboard
save_steps: 100
stage: kto
template: qwen3
trust_remote_code: true
val_size: 0.01
warmup_steps: 0
